title: "Key Extraction Status Page"
name: key_extraction_status_page
description: ""
defaultLocale: en
baseUrl: "https://status.nuos.io"
locales:
  - code: en
    iso: en-US
    name: English
    file: en.json
content:
  frontMatterFormat: yaml
  systems:
    - dropbox
    - edge
    - chrome
    - zscaler
    - lsass_win10_2004
    - lsass_win10_1909
    - lsass_winserv2019
    - lsass_winserv2016
    - lsass_winserv2012
    - openssl_fips
    - openssl_111
    - openssl_110
    - nss
