title: "Key Extraction Status Page"
name: key_extraction_status_page
description: ""
defaultLocale: en
baseUrl: "https://status.nuos.io"
locales:
  - code: en
    iso: en-US
    name: English
    file: en.json
content:
  frontMatterFormat: yaml
  systems:
    - dropbox
    - edge
    - chrome
    - zscaler
    - lsass
    - openssl
    - nss
